### ISSUE TITLE
XmlRpc::XmlRpcValue footprint Validity checking

### ISSUE THREAD

**Issue by nznobody** [ethz-asl/traversability_estimation#26]
Hello,

I was trying to use this node and spent some time finding out why my node would segmentation fault with XmlRpc::XmlRpcValue initialiser errors. The culprit has been located to [this line](https://github.com/ethz-asl/traversability_estimation/blob/master/traversability_estimation/src/TraversabilityMap.cpp#L69). With the [default config file parameters](https://github.com/ethz-asl/traversability_estimation/blob/master/traversability_estimation/config/default.yaml#L13).

The node would always segment fault. Adding in the following resolves the immediate issue and gives the user better feedback:

```
if (footprint.valid())
{
  if (footprint.size() < 3)
  {
    ...
  }
}
else
{
  ...
  ROS_WARN("Invalid footprint/footprint_polygon paramater parsed, using defaults");
}
```

Also, what is a correct way to parse this value then?

Thanks

**Comment by martiwer** [comment]
Thanks for the comment!

The footprint parameters were not set on the parameter server, but this is fixed now. The footprint of the robot is defined in the file [/config/robot_footprint.yaml](https://github.com/ethz-asl/traversability_estimation/blob/master/traversability_estimation/config/robot_footprint.yaml). I also added a check if the parameter is retrieved from the parameter server such that no more segmentation fault should appear.
